- name: Clone a git repository 'api-server' into /opt.
  git:
    repo: https://gerrit.akraino.org/r/regional_controller/api-server.git
    version: master
    dest: /opt/api-server

- name: Change the working directory to /opt/api-server/scripts and run start_arc.sh
  shell: ./start_arc.sh
  args:
    chdir: /opt/api-server/scripts

- debug: msg="Regional Controller is started. Web interface URL{{ ':' }} https{{ ':' }}//{{ rc_host }}"

